name = "doowee"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"
assets = { directory = "./build/client" }

[build]
command = "npm run build"
